### ISSUE TITLE
Generated HTML not ideal

### ISSUE THREAD

**Issue by jamienk** [train255/simplebutton#2]
Why not generate HTML like this:

```
<button class='simplebutton'><a href='link'>text</a></button>
```

**Comment by train255** [comment]
Because the anchor tag inside button tag does not work in Firefox

**Comment by train255** [comment]
In version 0.0.3, it generate only anchor tag
`<a class='simple-button-plugin' href='link'>Text</a>`

**Comment by eberhardst** [comment]
Can you install a select box for the next update, for target: _blank and target: _self?
I might be able to help you with this.
greeting
Eberhard

**Comment by train255** [comment]
> Can you install a select box for the next update, for target: _blank and target: _self?
> I might be able to help you with this.
> greeting
> Eberhard

Yes, I will do it. Thank you
