### ISSUE TITLE
Button Color problem

### ISSUE THREAD

**Issue by Gasygasy** [train255/simplebutton#3]
I created three buttons with different colors each. I changed the color of one button and hit OK then click on another button without **changing anything** and hit OK. The background color of this button changed

**Comment by train255** [comment]
Thank you for that positive feedback. I’ll try to fix this bug

**Comment by train255** [comment]
I fixed it. Thank you very much

**Comment by Gasygasy** [comment]
Cool!!

Thanks for your update

2018-06-14 7:24 GMT+03:00 train255 <notifications@github.com>:
